name: echo
description: A app designed to help (partially) blind people to go to the supermarket.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  provider: ^6.0.0
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  cloud_firestore: ^5.4.4
  speech_to_text: ^7.0.0
  flutter_barcode_scanner: ^2.0.0
  google_maps_flutter: ^2.9.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  geolocator: ^13.0.2
  flutter_tts: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/echo_logo.png